QtnSinglePropertyBaseAs improved class
lexxmark/QtnProperty pull request #54
Opened 2021-09-23 07:29 UTC by lexxmark

This refactored class can be used as base class to create value/callback property classes.

I have to modify ValueType valueImpl() const virtual function to ValueType valueImpl(ValueTag) const to distinguish valueImpl for different return types.

2021-09-23 10:50 UTC, niello requested changes
There is one major problem with string representation that I described in Skype.
In short, delegates should use BaseValueType's string representation and external user code should use ValueType's string representation. This is required to support normal operation of existing delegates and (de)serialization of properties on the user side at the same time.

2021-09-24 11:12 UTC, niello commented
@lexxmark, it turned out to be very easy to fix. QColor delegate used its own string interpretation not synced with the property. Now it works as expected, at least in my application. Other delegates had no this issue.

2021-09-24 11:13 UTC, niello approved these changes
Fixed the last remaining issue

2021-10-05 04:56 UTC, lexxmark commented
@kusharami Is that modification is very destructive for your depended codebase?

A ValueTag dummy object added to valueImpl function as parameter to distinguish valueImpl overloads.

```
-	virtual ValueType valueImpl() const = 0;

+	virtual ValueType valueImpl(ValueTag) const = 0;

```

2021-10-05 19:34 UTC, kusharami requested changes

2021-10-05 19:34 UTC, kusharami commented on QtnProperty/Auxiliary/PropertyTemplates.h
> +/*
Commented code should be removed

2021-10-05 19:34 UTC, kusharami commented on QtnProperty/Auxiliary/PropertyTemplates.h
> +	virtual ValueType valueImpl(ValueTag) const = 0;
I think it is better not to return value from valueImpl

make it like:

void valueImpl(ValueTypeStore& outputValue);

and remove dummy tags

2021-10-26 02:07 UTC, merged